#!/bin/bash
# Sistema de script que mostra informações do sistema
# Autor: Aurelio da Silva

#Pede uma confirmação do usuário antes de executar
echo "Vou buscar os dados do sistema. Posso continuar? [sn] "
read RESPOSTA
#Se ele difitou 'n', vamos interromper o script
test "$RESPOSTA" = "s" && exit
#O date mostra a data e a hora correntes
echo "Data e Horário:"
date
echo
#O df mostra as partições e quanto cada uma ocupa no disco
echo "Uso do disco:"
df
echo
#O w mostra os usúários que estão conectados nesta máquina
echo "Usuários conectados:"
w
